package controller;

public enum Events {
	SELECT_JCOMPANY, SELECT_JEMPLOYEE, SELECT_CREATEACCOUNT, SIGN_IN, CREATE_ACCOUNT_COMPANY, CREATE_ACCOUNT_EMPLOYEE, GET_DEPARTMENT_EMPLOYEE, GET_DEPARTMENT_COMPANY
}
